import React from 'react';
import Link from 'next/link';
import ScrollToTop from './scroll-to-top'
import Head from 'next/head'

export default function Layout({ children }) {
    return (
        <div>
            <Head>
                <title>Store apprication</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="max-w-screen-xl mx-auto px-6 md:px-8 lg:px-10 text-center mb-4">
                <h1 className="
                text-4xl
                md:text-5xl
                lg:text-6xl
                mb-4">Washing mashine store</h1>
                <p className="mb-1">This is demo apprication, you can create, update, delete product</p>
                <p>Let&apos;s try🙌</p>
            </header>

            <main>
                <article className="max-w-screen-xl mx-auto px-6 md:px-8 lg:px-10">
                    {children}
                </article>
            </main>

            <footer className="mb-6 md:mb-8 lg:mb-10 text-center">
                <ScrollToTop />
                <p className="text-sm">
                    &copy; 2022 <Link className="hover:underline" href={`/`}>Sayadesign.art</Link>
                </p>
            </footer>
        </div>
    );
}