import React from 'react';
import Link from 'next/link';
import ScrollToTop from './scroll-to-top'
import Head from 'next/head'
import FloationgActionButton from './floationg-action-button'

export default function Layout({ children }) {
    return (
        <div>
            <Head>
                <title>Store apprication</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <div className="relative"> */}
            <header className="max-w-screen-xl mx-auto px-6 md:px-8 lg:px-10 text-center my-10">
                <Link className="cursor-pointer" href={`/`}>
                    <h1 className="
                text-4xl
                md:text-5xl
                lg:text-6xl
                mb-4">Washing mashine store</h1>
                </Link>
                <p className="mb-1">This is demo apprication,
                    you can create, update, delete product
                    <span className="md:block">Let&apos;s try🙌</span>
                </p>
            </header>

            <main>
                <article className="max-w-screen-xl mx-auto px-6 md:px-8 lg:px-10">
                    {children}
                </article>

                {/* <div className="fixed right-20 buttom-20"> */}
                <FloationgActionButton />{/* </div> */}
            </main>

            <footer className="mt-10 mb-6 md:mb-8 lg:mb-10 text-center">
                <ScrollToTop />
                <p className="text-sm">
                    &copy; 2022 <Link className="hover:underline" href={`/`}>Sayadesign.art</Link>
                </p>
            </footer>

          
           {/*  </div> */}
        </div>
    );
}